# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
        DATABASE: ${{ secrets.DATABASE }}
        DATABASE_SCHEMA: ${{ secrets.DATABASE_SCHEMA }}
        DBUSERNAME: ${{ secrets.DBUSERNAME }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
    - run: npm ci
    - run: npm test -Parg1=$PASSWORD -Parg2=$DBUSERNAME
